---
  extends:
    eslint-config-airbnb

  parser:
    babel-eslint

  settings:
    ecmascript: 7

  parserOptions:
    ecmaFeatures:
      jsx: true
      modules: true
      destructuring: true
      experimentalObjectRestSpread: true
      experimentalDecorators: true
      classes: true
      forOf: true
      blockBindings: true
      arrowFunctions: true

  env:
    browser: true

  rules:
    # -------------
    # General Rules
    # -------------

    arrow-body-style: 0
    arrow-parens: 0
    no-param-reassign: 0
    no-new: 0
    consistent-return: 0
    key-spacing: 0
    no-multi-spaces: 0
    one-var: 0
    global-require: 0
    class-methods-use-this: 0
    comma-dangle: ["error", {
      "arrays": "always-multiline",
      "objects": "always-multiline",
      "imports": "always-multiline",
      "exports": "always-multiline",
      "functions": "never"
    }]
    func-names: 0
    indent: 2
    jsx-quotes: [2, "prefer-single"]
    new-cap: 0
    no-plusplus: 0
    no-return-assign: 0
    quote-props: 0
    template-curly-spacing: 0
    no-unused-expressions: 0


    # ------------
    # Import Rules
    # ------------

    import/extensions: 0
    import/no-extraneous-dependencies: 0
    import/no-unresolved: 0
    import/prefer-default-export: 0


    # -----------
    # React Rules
    # -----------

    react/forbid-prop-types: 0
    react/jsx-boolean-value: 0
    react/no-find-dom-node: 0
    react/jsx-curly-spacing: 0
    react/jsx-filename-extension: 0
    react/prefer-stateless-function: 0
    react/require-default-props: 0

    # --------------
    # jsx-a11y Rules
    # --------------

    jsx-a11y/no-static-element-interactions: 0
    jsx-a11y/no-noninteractive-element-interactions: 0
